// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jaspersolutions.contacts.domain;

import com.jaspersolutions.contacts.domain.Contact;
import com.jaspersolutions.contacts.domain.ContactDataOnDemand;
import com.jaspersolutions.contacts.domain.ContactType;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ContactDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContactDataOnDemand: @Component;
    
    private Random ContactDataOnDemand.rnd = new SecureRandom();
    
    private List<Contact> ContactDataOnDemand.data;
    
    public Contact ContactDataOnDemand.getNewTransientContact(int index) {
        Contact obj = new Contact();
        setAddress(obj, index);
        setContactType(obj, index);
        setContentType(obj, index);
        setFirstName(obj, index);
        setImage(obj, index);
        setLastName(obj, index);
        setPhone(obj, index);
        return obj;
    }
    
    public void ContactDataOnDemand.setAddress(Contact obj, int index) {
        String address = "address_" + index;
        obj.setAddress(address);
    }
    
    public void ContactDataOnDemand.setContactType(Contact obj, int index) {
        ContactType contactType = ContactType.class.getEnumConstants()[0];
        obj.setContactType(contactType);
    }
    
    public void ContactDataOnDemand.setContentType(Contact obj, int index) {
        String contentType = "contentType_" + index;
        obj.setContentType(contentType);
    }
    
    public void ContactDataOnDemand.setFirstName(Contact obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void ContactDataOnDemand.setImage(Contact obj, int index) {
        byte[] image = String.valueOf(index).getBytes();
        obj.setImage(image);
    }
    
    public void ContactDataOnDemand.setLastName(Contact obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void ContactDataOnDemand.setPhone(Contact obj, int index) {
        String phone = "phonexxx_" + index;
        if (phone.length() > 10) {
            phone = new Random().nextInt(10) + phone.substring(1, 10);
        }
        obj.setPhone(phone);
    }
    
    public Contact ContactDataOnDemand.getSpecificContact(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Contact obj = data.get(index);
        Long id = obj.getId();
        return Contact.findContact(id);
    }
    
    public Contact ContactDataOnDemand.getRandomContact() {
        init();
        Contact obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Contact.findContact(id);
    }
    
    public boolean ContactDataOnDemand.modifyContact(Contact obj) {
        return false;
    }
    
    public void ContactDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Contact.findContactEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Contact' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Contact>();
        for (int i = 0; i < 10; i++) {
            Contact obj = getNewTransientContact(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
